### ISSUE TITLE
[QoL]Ethereal changes

### ISSUE THREAD

**Issue by Xenofyre** [Whitesands13/Whitesands#304]
At the behest of Mald, I bring some ideas of change to Ethereals. As of now, no one plays them. While I cannot speak for every individual, from ym own experiences they are simply inconvenient to play. Any small benefits they have are overshadowed by constantly micromanaging your charge level. I know others have shared the sentiment in the past when complaining about it.

To fix this issue my ideas are as follows. Make your exact charge level visible from your info/ic tab. Currently there is no way to actually check it(that I know of) This should be easily accessible information considering failure to manage it can literally kill you. Next, managing your charge needs to be much easier. As of now, you need to go stand at an APC or a light bulb and give it the succ for 1-2 minutes at a time every 5 minutes. You can use the borg rechargers if one is near by, but with the inability to track your charge, its easy to overcharge on them.

Next, make your charge drain much slower. Even from full, it takes around 5-10 minutes before you need to go charge again. And with how long it takes to charge unless using a borg charger, you end up spending a sizable amount of your playtime simply keeping yourself alive. 
Finally, give Ethereals an ability to discharge anything above 100%. As of now, you simply take toxin damage, scaling with how over charged you are. At very high levels, you randomly shoot off tesla bolts. The Ethereal discharge I am proposing would be voluntary. Ideally scaling from a small 1 damage burn(like a static shock) if used on another person all the way to a single use discharge of the tesla bolts they currently fire with all its same effects. The toxin damage you will take simply acquiring this charge level is already punishing enough, though a total stamina drain could also be added to this for balancing factor.

**Comment by tiramisuapimancer** [comment]
as an ethereal player, fucking please, because good god it's like playing a diabetic

**Comment by triplezeta** [comment]
what tira said

**Comment by tiramisuapimancer** [comment]
Ideasguy idea number 1)
Give Ethereals an ability akin to a lighter or an igniter that can do all of the things those items can do: cigarettes, burn paper, heat beakers

Ideasguy 2. 
Multitool interaction. Right now multitools do a low-damage attack to everything even on help intent, but since ethereals are electric and interact with other electricity based things (emps and emags) I think it'd be neat if they had some kind of multi tool interaction. My current idea is permanently changing their color to a random one. So you can spam it to get the color you want or use it to piss off ethereals you don't like. If anyone has literally any better ideas please post them 

Ideasguy #3 
Like some other abilities that cost charge or some shit i dunno. .Be more fun if they were utility rather than 

Ideasguy 5 
In exchange for all the cool shit you give em it might be worth it to make EMPs damage them (toxin like all other charge based damaage) or or stun them drain their power because IIRC at the moment the emp only gives them turns their light off and gives mad mood, just as a nerf, since having Shite power as a nerfing factor is unfun to play with compared to being emp weak (but not as much as ipcs obvi)

Ideasguy six
FOr the love of god someone make me write lore on them  (me)

VII
Oh yeah also right now energy bars FUCKING SUCK and give you next to no charge, they are completely useless. Id buff the unit amount of liquid electricity in them (its like 3u at the moment). I also think it would be pretty Gamer if there was, for perhaps, a buyable drink at soda machines that was listed as a HYPER POWER SUPER MEGABITCH N-R-G DRINQUE!!!! and it contained some combination of LE and some sort of other stimulating reagents (coffee, epinephrine, pump up, monke energy some sort of sodsa, 13 loko? one of them someting). If this was too much it may have to be a contraband item to make it different from the bars

**Comment by tiramisuapimancer** [comment]
Okay, another thing that needs to be touched up with Ethereals: They can select beards, but the beards do not actually show up as hairs do. It's a bug I think would do good to be fixed.

Also, I think it'd be neat if they both took and gave more power to APCs than they currently do: at the moment, charging from low to full  is less than ten percent of the APC- often less than five. I haven't looked at exact numbers.
In comparison IPCs take out noticable chunks of APC charge every time they charge, though they also do so faster and require it to be done less (as IPC charge is literally hunger- nutriment in IPCs systems charges then, and IPC charging implants instead placed in an organic will feed them when used, flawlessly. Ethereals have nohunger and use an entirely different thing)

**Comment by untrius** [comment]
For ease of reference, I wanted these requests in the form of a numbered list:
1. Make charge level visible from status tab (done)
2. Make charge management easier (nebulous)
3. Make charge drain slower
4. Intentional discharge of overcharge
5. Lighter ability
6. Multitool interaction i.e. color change
7. Abilities that cost charge
8. Take some form of damage from EMPs
9. Buff energy bars
10. Drink containing Liquid Electricity
11. Ethereal beards (done)
12. Raise amount of charge taken from/given to APCs

**Comment by untrius** [comment]
In regards to number 3, it takes about 27 minutes to go from 100% charge to 0%.  The first warning and negative moodlet come at 50%, and the second at 20%.  So to avoid the moodlets, you're charging about every 13 minutes.  I agree that this feels way too often.  In my opinion charging around 10%/24-minutes feels more reasonable.  So I think lowering the warnings/moodlets to something like 35% and 15% would make this more bearable without buffing the max time between charges.

That said, buffing the max time between charges to around 40 minutes is probably also a reasonable option.

**Comment by untrius** [comment]
As for number 4, I find myself wanting this a lot.  For me it would be enough to just be able to discharge into a full APC.  I'm guessing the reason you can't is so you don't accidentally dump all your charge acting as a ghetto inducer, when a cell was actually full the whole time.  So I would find it reasonable to allow you to do it, but have the APC send you a warning message when you do.

**Comment by dinnerwoerror** [comment]
cant we just make it an hour and a half and give you the ability to get a bigger power cell

**Comment by untrius** [comment]
Number 3: I feel like 90 minutes is too long.  At that point you're typically only charging once per round.  Given that this will definitely have an impact on number 7, I think it might be better to wait until that's more fleshed out to make a decision here.  That said, I've found a sort of workaround.  There's no health penalty in the range 20 to 125, so this gives us 28-29 minutes between charges.  Plus you can usually sleep off the toxin damage if you go under 20.  I can live with this for now.

I do really like the idea of the extended capacity crystal, but it's a slightly bigger change.

**Comment by untrius** [comment]
Number 4: Given that the range 100 to 125 only has a mood penalty that can be offset with a shower, and 125+ will make you almost immediately discharge; I'm not sure this is needed at this time.

**Comment by dinnerwoerror** [comment]
i mean like, i fill up on gas every 90 minutes so i donno about you

**Comment by untrius** [comment]
That's a fair point.  I was trying to compare it to how often humans have to eat, but it's a bit tricky since it depends on how much they move and where their hunger level starts.   If they're running nonstop, I believe it's about 35 minutes to go from middle of not-hungry (350) to starving (150), but 80 minutes if they're still.  Charging and eating are probably equally easy/hard, so I suppose raising it would bring it closer to balanced.

**Comment by dinnerwoerror** [comment]
why is gas a controlled substance but not cheesy nachos or electricity
those both kill you just as much

**Comment by dee-dubya** [comment]
Plasmeme internals are balanced around...well, internals tanks. Ethereal charge should be balanced around typical hunger, not emergency o2 tank capacity.

**Comment by untrius** [comment]
If you have an opinion on how long Ethereal charge should last (number 3), please take a look at PR 525.  It has a chart with different possible times and the values to set them.
